apiVersion: apps/v1
kind: Deployment
metadata:
  name: biz
  labels:
    app: biz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biz
  template:
    metadata:
      labels:
        app: biz
    spec:
      containers:
      - name: biz
        image: biz:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: biz-service
spec:
  selector:
    app: biz
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
